#!/usr/bin/env bash
# Usage: agency vanity
# Summary: Check Twitter followers count
# Help: Uses the t gem to check followers for a given Twitter user
#
#    agency vanity [username]

set -e
for twittername in agencyrev revstatus michaeljans chowzer24 lucasjans stephencway joshuamonen kungfookenny; do
	USERNAME=${1:-"$twittername"}
	echo $USERNAME $(t user $USERNAME | grep Followers | cut -d " " -f 5)
done
