#!/usr/bin/expect -f
# Usage: agency telnet
# Summary: Telnet to Agency Revolution servers
# Help: Uses telnet to our server
#
#    agency telnet

set timeout 20
set IPaddress "192.168.168.220"
set Username "@quantumclub.local"
set Password ""
set Directory .

log_file -a $Directory/session_$IPaddress.log
send_log "### /START-TELNET-SESSION/ IP: $IPaddress @ [exec date] ###\r"

spawn telnet $IPaddress
expect "login: "
send "$Username\r"
expect "password: "
send "$Password\r"
expect "C:\>"
send "cd Web 2/AR-Clients/Portals\r"
interact
send_log "\r### /END-TELNET-SESSION/ IP: $IPaddress @ [exec date] ###\r"
exit
