#!/usr/bin/env bash
# Usage: agency portal
# Summary: Open, edit or preview a portal
# Help: Open, edit or preview a portal
#
#    agency portal [images] [name]
#    agency portal [edit] [name]
#    agency portal [sass] [name]
#    agency portal [js] [name]
#    agency portal [view] [name]
#    agency portal [clean] [name]
#    agency portal [copy] [target] [destination]
#    agency poratl [watch] [name]

set -e

ACTION=${1}
PORTALNAME=${2}
PORTALSDIR="/shares/AR-Clients/Portals"
DESTPORTALNAME=${3}

case $ACTION in

	edit )
	if [ -d $PORTALSDIR/$PORTALNAME ]; then
		cd $PORTALSDIR/$PORTALNAME/
		$EDITOR .
	else
		echo "Portal $PORTALNAME does not exist"
	fi
	;;

	sass )
	if [ -f $PORTALSDIR/$PORTALNAME/sass/portal.scss ]; then
		$EDITOR $PORTALSDIR/$PORTALNAME/sass/portal.scss
  elif [ -f $PORTALSDIR/$PORTALNAME/sass/portal2.scss ]; then
		$EDITOR $PORTALSDIR/$PORTALNAME/sass/portal2.scss
  else
    echo "Sass files do not exist in this portal"
	fi
	;;

	js )
	if [ -f $PORTALSDIR/$PORTALNAME/portal.js ]; then
		$EDITOR $PORTALSDIR/$PORTALNAME/portal.js
  elif [ -f $PORTALSDIR/$PORTALNAME/portal2.js ]; then
		$EDITOR $PORTALSDIR/$PORTALNAME/portal2.js
  else
    echo "Javascript files do not exist in this portal"
	fi
	;;

	images )
	if [ -d $PORTALSDIR/$PORTALNAME/images ]; then
		cd $PORTALSDIR/$PORTALNAME/images && ls
	else
		echo "Images folder does not exist"
	fi
	;;

	view )
	open http://$PORTALNAME.agencyrevolution.com
	;;

  clean )
  for FILE in portal.bak.css
  do
 #   if [ -f $PORTALSDIR/$PORTALNAME/$FILE ]; then
      rm -rf $PORTALSDIR/$PORTALNAME/$FILE
 #   else
 #     echo "$FILE does not exist"
 #   fi
  done
  for FOLDER in css
  do
 #   if [ -d $PORTALSDIR/$PORTALNAME/$FOLDER ]; then
      rm -rf $PORTALSDIR/$PORTALNAME/$FOLDER
 #   else
 #     echo "$FOLDER does not exist"
 #   fi
  done
  ;;
  
  copy )
  for FILE in config.rb Gemfile portal.js portal2.js portal.css portal2.css
  do
    if [ -f $PORTALSDIR/$DESTPORTALNAME/$FILE ]; then
      rm -rf $PORTALSDIR/$DESTPORTALNAME/$FILE
    else
      echo "$FILE does not exist, copying into $DESTPORTALNAME"
      cp $PORTALSDIR/$PORTALNAME/$FILE $PORTALSDIR/$DESTPORTALNAME/$FILE
    fi
  mkdir -p $PORTALSDIR/$DESTPORTALNAME/sass 
  for SASSFILE in portal.scss portal2.scss
  do
    if [ -f $PORTALSDIR/$DESTPORTALNAME/sass/$SASSFILE ]; then
      rm -rf $PORTALSDIR/$DESTPORTALNAME/sass/$SASSFILE
    else
      echo "$SASSFILE does not exist, copying into $DESTPORTALNAME"
      cp $PORTALSDIR/$PORTALNAME/sass/$SASSFILE $PORTALSDIR/$DESTPORTALNAME/sass/$SASSFILE
    fi
  done
  done
  ;;
  
  watch )
    if [ -f $PORTALSDIR/$PORTALNAME/config.rb ]; then
      compass watch $PORTALSDIR/$PORTALNAME
    else
      echo "$PORTALNAME is not configured yet."
    fi
  ;;

  compile )
    if [ -f $PORTALSDIR/$PORTALNAME/config.rb ]; then
      compass compile $PORTALSDIR/$PORTALNAME
    else
      echo "$PORTALNAME is not configured yet."
    fi
  ;;

esac

