#!/usr/bin/env bash
# Usage: agency foundry
# Summary: Check and install the Foundry gem
# Help: Searches for an installed Foundry gem and installs it
#
#    agency foundry [gem]

set -e

success () {
	printf '\033[0;32m%s\033[0m\n'
	printf '\033[0;32m%s\033[0m\n' " $1 "
	printf '\033[0;32m%s\033[0m\n'
}

fail () {
	printf '\033[0;32m%s\033[0m\n'
	printf '\033[0;31m%s\033[0m\n' " $1 "
	printf '\033[0;32m%s\033[0m\n'
}

GEM=${1:-"foundry"}
check='gem which $GEM | grep "/$GEM.rb"'
if [ ! "$check" = "ERROR:  Can't find ruby library file or shared library $GEM" ]; then
	# Do nothing
	fail "$GEM is already installed"
else
	echo 'Installing $GEM'
	case "$GEM" in
		foundry )
			if [ sudo gem install foundry --source https://gems.gemfury.com/PeHELUxDnzyAssaJAzKS/ ]; then
				success "Successfully installed $GEM"
			else
				fail "$GEM failed to install"
			fi
			;;
		* )
			if [ sudo gem install $GEM ]; then
				success "Successfully installed $GEM"
			else
				fail "$GEM failed to install"
			fi
	esac
fi
